import type { Bi } from '../data/types'

export interface HelpArticle {
  path: string
  title: Bi
  what: Bi
  steps: { ar: string[]; en: string[] }
  tip?: Bi
}

type Row = [path: string, tAr: string, tEn: string, wAr: string, wEn: string, sAr: string[], sEn: string[], tip?: [string, string]]

const rows: Row[] = [
  [
    '/',
    'لوحة القيادة',
    'Dashboard',
    'الصفحة الأولى بعد الدخول: تعرض ما يخصّك أنت فقط — ما ينتظر اعتمادك، وأرصدة الصناديق، وحالة المشاريع، والمكاتب على الخريطة.',
    'Your first page after signing in. It shows only what concerns you — items waiting for your approval, fund balances, project status, and offices on the map.',
    ['ابدأ بالبطاقات العلوية: كل رقم فيها قابل للضغط ويأخذك إلى التفاصيل.', 'اضغط على أي مكتب في الخريطة لتصفية اللوحة على هذا المكتب.', 'قائمة «ابدأ من هنا» تقترح أول الخطوات المناسبة لدورك.'],
    ['Start with the cards at the top — every number is clickable and takes you to the details.', 'Click an office on the map to filter the dashboard to that office.', 'The “Get started” list suggests the first steps that fit your role.'],
  ],
  [
    '/projects',
    'المشاريع والميزانيات',
    'Projects & budgets',
    'كل مشروع مقسّم إلى محاور، وكل محور إلى بنود. لكل مستوى سقف، ولا يمرّ صرف يتجاوز السقف إلا بإعادة تخصيص معتمدة.',
    'Each project is split into pillars, and each pillar into budget lines. Every level has a ceiling, and no spending above it goes through without an approved reallocation.',
    ['افتح المشروع لترى المحاور، ثم افتح المحور لترى البنود.', 'الشريط الملوّن يوضح: المصروف (داكن)، والمحجوز (برتقالي)، وتحت الاعتماد (مخطط)، والمتبقي.', 'لنقل مبلغ من بند إلى آخر استخدم «إعادة تخصيص» — تمرّ على سلسلة اعتماد.'],
    ['Open a project to see its pillars, then a pillar to see its lines.', 'The coloured bar shows spent (dark), committed (orange), in approval (striped) and what is left.', 'To move money between lines use “Reallocate” — it goes through an approval chain.'],
    ['المتاح = السقف − المصروف − المحجوز − ما تحت الاعتماد. هذا هو الرقم الذي يتحقق منه النظام عند كل طلب.', 'Available = ceiling − spent − committed − in approval. This is the figure the system checks on every request.'],
  ],
  [
    '/requests',
    'طلبات الصرف',
    'Spend requests',
    'جميع طلبات الصرف من كل المكاتب (أو مكتبك فقط حسب صلاحيتك)، مع مرحلة الاعتماد الحالية لكل طلب.',
    'All spend requests from every office (or just yours, depending on your access), with the approval stage of each.',
    ['استخدم المرشحات أعلى الجدول للبحث حسب الحالة أو المكتب.', 'افتح الطلب لترى سجل الاعتماد: من وافق ومتى، ومن ينتظر.', 'بعد الاعتماد النهائي يظهر الطلب للمالية في «سندات الصرف» للدفع.'],
    ['Use the filters above the table to search by status or office.', 'Open a request to see its approval trail — who approved, when, and who is next.', 'Once fully approved, the request appears to Finance under “Vouchers” for payment.'],
  ],
  [
    '/requests/new',
    'طلب صرف جديد',
    'New spend request',
    'نموذج من خطوات قصيرة. يختار النظام سلسلة الاعتماد تلقائياً حسب المبلغ والمكتب، ويوقفك قبل تجاوز السقف.',
    'A short step-by-step form. The system picks the approval chain from the amount and office, and stops you before you exceed a ceiling.',
    ['اختر المشروع ثم المحور ثم البند — يظهر لك المتاح فوراً.', 'أدخل المبلغ: إذا تجاوز المتاح يظهر تحذير مع اقتراح إعادة التخصيص.', 'راجع سلسلة الاعتماد المقترحة ثم أرسل.'],
    ['Pick the project, then the pillar, then the line — the available amount appears immediately.', 'Enter the amount: if it exceeds what is available you get a warning and a reallocation suggestion.', 'Review the proposed approval chain, then submit.'],
    ['يمكن فتح هذا النموذج من صفحة النشاط الميداني ليُملأ تلقائياً بالنشاط والمبلغ.', 'You can open this form from a field activity page and it fills in the activity and amount for you.'],
  ],
  [
    '/approvals',
    'بانتظار اعتمادي',
    'Awaiting my approval',
    'الطلبات التي وصلت إلى دورك في سلسلة الاعتماد فقط.',
    'Only the requests that have reached your step in the approval chain.',
    ['افتح الطلب لترى أثره على البند قبل وبعد.', 'اعتمد أو ارفض مع ملاحظة — الملاحظة تصل لصاحب الطلب كتنبيه.', 'الرقم الأحمر بجانب القائمة يخبرك بعدد ما ينتظرك.'],
    ['Open a request to see its effect on the budget line before and after.', 'Approve or reject with a note — the note reaches the requester as a notification.', 'The red number beside the menu tells you how many are waiting.'],
  ],
  [
    '/activities',
    'الأنشطة الميدانية',
    'Field activities',
    'كل نشاط (عيادة متنقلة، توزيع، توعية…) مربوط بمشروع وبند، وله تقرير فني وصرف مالي. هنا تتابع الاثنين معاً.',
    'Every activity (mobile clinic, distribution, awareness…) is tied to a project line and has a field report and spending. Here you follow both together.',
    ['الحالة توضح هل رُفع التقرير الفني وهل صُرف المال.', 'افتح النشاط لترى التقرير والمصروفات المرتبطة به.', 'من صفحة النشاط يمكنك طلب صرف مرتبط به مباشرة.'],
    ['The status shows whether the field report is in and whether money was spent.', 'Open an activity to see its report and linked expenses.', 'From the activity page you can raise a spend request linked to it directly.'],
  ],
  [
    '/activities/report',
    'رفع تقرير فني',
    'Submit a field report',
    'نموذج مبسّط يعمل حتى دون إنترنت: يُحفظ التقرير في الجهاز ويُرسل تلقائياً عند عودة الاتصال.',
    'A simple form that works even without internet: the report is kept on the device and sent automatically when the connection returns.',
    ['اختر النشاط، ثم أدخل عدد المستفيدين والملاحظات.', 'إذا انقطع الاتصال يُحفظ التقرير على الجهاز ويظهر شريط «بانتظار الإرسال».', 'عند عودة الاتصال يُرسل تلقائياً، أو اضغط زر الإرسال في الشريط.'],
    ['Pick the activity, then enter beneficiary numbers and notes.', 'If the connection drops, the report is kept on the device under “waiting to send”.', 'When you are back online it sends automatically, or press the send button in the bar.'],
  ],
  [
    '/reconciliation',
    'المطابقة الفنية والمالية',
    'Report matching',
    'تحلّ مشكلة اختلاف توقيت التقارير الفنية والمالية: تعرض الصرف الذي لا تقرير له، والتقارير التي لا صرف لها، وتقترح المطابقات.',
    'Solves the timing gap between field and finance reports: it lists spending with no report, reports with no spending, and suggests matches.',
    ['ابدأ بالمطابقات المقترحة — اضغط «ربط» إذا كانت صحيحة.', 'الصرف بلا تقرير يُرسل تنبيهاً لمسؤول المكتب بعد عدد الأيام المحدد في قواعد التنبيهات.', 'الأنشطة العينية (من التغذية) لا تحتاج صرفاً نقدياً ولا تظهر كفجوة.'],
    ['Start with the suggested matches — press “Link” if they are right.', 'Spending without a report sends a reminder to the office lead after the days set in notification rules.', 'In-kind activities (funded from supplies) need no cash and do not show as gaps.'],
  ],
  [
    '/activities/import',
    'الاستيراد من Excel',
    'Import from Excel',
    'للمكاتب ضعيفة الاتصال: نزّل القالب، املأه دون إنترنت، ثم ارفعه هنا عند توفّر الاتصال.',
    'For offices with weak internet: download the template, fill it in offline, then upload it here when you have a connection.',
    ['نزّل القالب الخاص بمكتبك — يحتوي قوائم منسدلة للأنشطة والقيم المسموحة.', 'بعد الرفع يعرض النظام كل صف: صالح أو به خطأ مع شرح الخطأ.', 'استورد الصفوف الصالحة فقط، وصحّح الباقي لاحقاً.'],
    ['Download your office’s template — it has drop-down lists for activities and allowed values.', 'After upload, every row is shown as valid or with an explained error.', 'Import the valid rows only and fix the rest later.'],
  ],
  [
    '/finance',
    'المالية — نظرة عامة',
    'Finance overview',
    'أرصدة النقد والبنوك بالدولار والجنيه، وما ينتظر الدفع، والعُهد المفتوحة، ونتيجة الشهر.',
    'Cash and bank balances in USD and SDG, what is waiting for payment, open advances and the month’s result.',
    ['البطاقات العلوية تأخذك إلى السندات والعُهد.', 'كل رقم محسوب من القيود مباشرة — لا إدخال يدوي للأرصدة.', 'الدفاتر بالدولار، وحسابات الجنيه تُعاد تقييمها في الإقفال الشهري.'],
    ['The top cards take you to vouchers and advances.', 'Every figure comes straight from journal entries — no balances are typed in by hand.', 'Books are kept in USD; SDG accounts are revalued at month-end close.'],
  ],
  [
    '/finance/accounts',
    'دليل الحسابات',
    'Chart of accounts',
    'شجرة الحسابات الخاصة بالمنظمة. يمكن إضافة حسابات جديدة وتعطيلها وربط كل نوع مصروف بحساب.',
    'The organisation’s account tree. You can add new accounts, deactivate them, and map each expense type to an account.',
    ['اضغط على حساب رئيسي لعرض الحسابات الفرعية وأرصدتها.', '«حساب جديد» يقترح رقماً تلقائياً تحت الحساب الأب.', 'الحساب الذي عليه حركات لا يُحذف، بل يُعطّل.'],
    ['Click a parent account to see its sub-accounts and balances.', '“New account” suggests the next code under the parent automatically.', 'An account with transactions cannot be deleted — deactivate it instead.'],
  ],
  [
    '/finance/vouchers',
    'سندات الصرف والقبض',
    'Payment & receipt vouchers',
    'دفع الطلبات المعتمدة وتسجيل المقبوضات. كل سند يُنشئ قيداً محاسبياً تلقائياً بأبعاد المشروع والبند والمكتب.',
    'Pay approved requests and record receipts. Each voucher creates a journal entry automatically, tagged with project, line and office.',
    ['تبويب «بانتظار الدفع» يعرض الطلبات المعتمدة.', 'اختر طريقة الدفع (نقداً، بنك، عهدة) والعملة.', 'رقم القيد المُنشأ يظهر في «قيود اليومية» للمراجعة.'],
    ['The “Awaiting payment” tab lists approved requests.', 'Choose how to pay (cash, bank, advance) and the currency.', 'The entry it creates appears under “Journal entries” for review.'],
  ],
  [
    '/finance/advances',
    'العُهد وتسويتها',
    'Cash advances',
    'صرف عهدة لموظف قبل النشاط، ثم تسويتها بالفواتير وإرجاع الباقي. العهدة المفتوحة تُحتسب محجوزة على البند.',
    'Give a staff member an advance before an activity, then settle it with receipts and return the balance. An open advance counts as committed on its budget line.',
    ['«عهدة جديدة»: اختر الموظف والنشاط والمبلغ وتاريخ الاستحقاق.', 'عند العودة: «تسوية» وأدخل المصروف الفعلي والمبلغ المُرجع.', 'العهد المتأخرة تظهر باللون الأحمر وتُرسل تذكيراً.'],
    ['“New advance”: pick the staff member, activity, amount and due date.', 'On return: “Settle” and enter actual spending and the amount returned.', 'Overdue advances show in red and send a reminder.'],
  ],
  [
    '/finance/journal',
    'قيود اليومية',
    'Journal entries',
    'كل القيود — التلقائية من السندات والرواتب والمخزون، واليدوية. لكل سطر أبعاد المشروع والبند والمكتب.',
    'All entries — automatic ones from vouchers, payroll and stock, and manual ones. Every line carries project, line and office dimensions.',
    ['ابحث برقم القيد أو الوصف.', 'القيد اليدوي لا يُحفظ إلا إذا تساوى المدين والدائن.', 'لا يمكن تعديل قيد في شهر مُقفل.'],
    ['Search by entry number or description.', 'A manual entry only saves when debits equal credits.', 'Entries in a closed month cannot be changed.'],
  ],
  [
    '/finance/rates',
    'أسعار الصرف',
    'Exchange rates',
    'سجل أسعار الجنيه مقابل الدولار. يُستخدم السعر في تاريخ كل حركة، ويُستخدم سعر نهاية الشهر لإعادة التقييم.',
    'The log of SDG/USD rates. Each transaction uses the rate on its date, and the month-end rate is used for revaluation.',
    ['أضف السعر الجديد عند تغيّره — لا حاجة لإدخاله يومياً.', 'المصدر (بنك السودان، السوق الموازي) يُحفظ للتدقيق.'],
    ['Add a new rate when it changes — no need to enter it daily.', 'The source (Central Bank, parallel market) is kept for audit.'],
  ],
  [
    '/finance/close',
    'الإقفال الشهري',
    'Monthly close',
    'قائمة تحقق قبل إقفال الشهر: لا طلبات معلّقة، العهد مسوّاة، إعادة تقييم العملة، ثم الإقفال.',
    'A checklist before closing the month: no pending items, advances settled, currency revalued, then close.',
    ['راجع كل بند في القائمة — الأحمر يحتاج معالجة.', '«إعادة التقييم» تُنشئ قيد فروق العملة تلقائياً.', 'بعد الإقفال لا يمكن إضافة قيود للشهر إلا بإعادة فتحه من مدير المالية.'],
    ['Go through each item — red ones need attention.', '“Revalue” creates the currency difference entry automatically.', 'After closing, no entries can be added to the month unless the finance manager reopens it.'],
  ],
  [
    '/finance/reports',
    'التقارير المالية',
    'Financial reports',
    'ميزان المراجعة، والميزانية مقابل الفعلي لكل مشروع وبند، وموقف النقد في كل صندوق.',
    'Trial balance, budget versus actual for every project and line, and the cash position of every fund.',
    ['اختر التقرير من التبويبات أعلى الصفحة.', 'أسفل ميزان المراجعة سطر يخبرك إذا كان الميزان متوازناً.', 'تقرير الميزانية مقابل الفعلي يُظهر نسبة الصرف لكل بند.'],
    ['Pick a report from the tabs at the top.', 'Below the trial balance a line tells you whether it balances.', 'Budget versus actual shows the spending rate of every line.'],
  ],
  [
    '/supply',
    'المخزون',
    'Stock',
    'أرصدة المواد في كل مستودع، والأصناف التي نزلت تحت الحد الأدنى، وقيمة المخزون.',
    'Item balances in every store, items below their minimum, and stock value.',
    ['الأصناف تحت الحد الأدنى تظهر أولاً بعلامة تحذير.', 'اضغط على صنف لترى حركاته.', 'التغذية العينية تُستلم من «استلام التغذية» وتدخل المخزون والحسابات معاً.'],
    ['Items below minimum appear first with a warning.', 'Click an item to see its movements.', 'In-kind replenishment is received under “Receive supplies” and enters stock and the books together.'],
  ],
  [
    '/supply/receipts',
    'استلام التغذية',
    'Receive supplies',
    'تسجيل المواد العينية الواردة (التغذية) أو المشتراة. يُنشئ حركة مخزون وقيداً بقيمة المواد.',
    'Record incoming in-kind replenishment or purchased goods. It creates a stock movement and an entry for their value.',
    ['اختر المصدر والمستودع.', 'أضف الأصناف والكميات والقيمة.', 'احفظ — يُرسل تنبيه للمكتب المعني.'],
    ['Pick the source and store.', 'Add items, quantities and value.', 'Save — the office concerned is notified.'],
  ],
  [
    '/supply/issues',
    'صرف المواد',
    'Issue stock',
    'صرف مواد من المستودع إلى نشاط ميداني. التكلفة تُحمّل على المشروع والبند.',
    'Issue materials from a store to a field activity. The cost is charged to the project line.',
    ['اختر النشاط — يُحدد المشروع والبند تلقائياً.', 'لا يُسمح بصرف أكثر من الرصيد المتوفر.'],
    ['Pick the activity — the project line follows automatically.', 'You cannot issue more than the available balance.'],
  ],
  [
    '/supply/items',
    'الأصناف',
    'Items',
    'قائمة الأصناف ووحداتها وحدودها الدنيا وفئاتها.',
    'The list of items, their units, minimum levels and categories.',
    ['عدّل الحد الأدنى لتحصل على تنبيه قبل نفاد الصنف.', 'الفئة تحدد الحساب المحاسبي للصنف.'],
    ['Adjust the minimum level to be warned before an item runs out.', 'The category decides the item’s ledger account.'],
  ],
  [
    '/logistics',
    'الشحنات',
    'Shipments',
    'لوحة الشحنات بين المستودعات والمكاتب: قيد التجهيز، في الطريق، تم الاستلام.',
    'The board of shipments between stores and offices: preparing, in transit, received.',
    ['«شحنة جديدة» تحجز المواد من المستودع.', '«انطلاق الشحنة» يسجلها في الطريق.', 'عند الاستلام أدخل الكميات الفعلية — أي نقص يُسجّل ويُحمّل تلقائياً.'],
    ['“New shipment” reserves the goods from the store.', '“Dispatch” marks it in transit.', 'On arrival enter actual quantities — any shortage is recorded and booked automatically.'],
  ],
  [
    '/logistics/fleet',
    'المركبات والوقود',
    'Vehicles & fuel',
    'المركبات وحالتها، وسجل تعبئة الوقود ومعدل الاستهلاك، ومواعيد الصيانة والترخيص.',
    'Vehicles and their status, the fuel log and consumption, and service and licence dates.',
    ['«تعبئة وقود» تسجّل اللترات والقيمة وعداد المسافة.', 'المعدل غير الطبيعي يظهر بلون مختلف.'],
    ['“Add fuel” records litres, cost and odometer.', 'Unusual consumption is highlighted.'],
  ],
  [
    '/patients',
    'سجل المستفيدين',
    'Beneficiary register',
    'ملف واحد لكل مريض أو مستفيد، يربط كل خدمة بالنشاط والمشروع الذي موّلها.',
    'One file per patient or beneficiary, linking each service to the activity and project that funded it.',
    ['ابحث أولاً بالاسم أو الهاتف قبل تسجيل شخص جديد.', 'عند التسجيل ينبّهك النظام إذا وُجد شخص مشابه.', 'افتح الملف لتسجيل خدمة جديدة.'],
    ['Search by name or phone before registering someone new.', 'While registering, the system warns you if a similar person already exists.', 'Open a file to record a new service.'],
    ['أرقام الهواتف محجوبة عمّن لا يملك صلاحية التعديل — حمايةً لخصوصية المرضى.', 'Phone numbers are hidden from roles without edit access, to protect patient privacy.'],
  ],
  [
    '/patients/stats',
    'إحصاءات المستفيدين',
    'Beneficiary statistics',
    'تصنيف المستفيدين حسب النوع والعمر والمكتب والخدمة — الأرقام نفسها في تقرير المقر.',
    'Beneficiaries by gender, age, office and service — the same figures used in the HQ report.',
    ['اختر مكتباً لتصفية كل الرسوم.', 'الرسم الشهري يوضح اتجاه الخدمات خلال 6 أشهر.'],
    ['Choose an office to filter every chart.', 'The monthly chart shows the service trend over 6 months.'],
  ],
  [
    '/hr',
    'الموظفون',
    'Staff',
    'ملف كل موظف: العقد والراتب والمكتب، والمشروع الذي يُحمّل عليه راتبه بالنسب.',
    'Each staff member’s file: contract, salary, office, and the project their salary is charged to, by percentage.',
    ['«موظف جديد» لفتح ملف.', 'في الملف حدد نسب التحميل على بنود المشاريع — الباقي يُحمّل على الإدارة العامة.', 'العقود التي تنتهي خلال 30 يوماً تظهر في الأعلى.'],
    ['“New staff member” opens a file.', 'In the file, set the share charged to each project line — the rest goes to general admin.', 'Contracts ending within 30 days are listed at the top.'],
  ],
  [
    '/hr/leave',
    'الإجازات',
    'Leave',
    'طلبات الإجازة واعتمادها، ورصيد كل موظف، ومن سيغيب هذا الأسبوع.',
    'Leave requests and approvals, each person’s balance, and who is away this week.',
    ['اعتمد أو ارفض الطلب — يُخصم من الرصيد تلقائياً.', 'قائمة الغائبين تساعد في جدولة الأنشطة الميدانية.'],
    ['Approve or reject — the balance is deducted automatically.', 'The “away” list helps you schedule field activities.'],
  ],
  [
    '/hr/payroll',
    'الرواتب',
    'Payroll',
    'كشف رواتب الشهر بالإجمالي والاستقطاعات والصافي، وتوزيع التكلفة على المشاريع، ثم ترحيله للحسابات.',
    'The month’s payroll with gross, deductions and net, the cost split across projects, then posting to the books.',
    ['اختر الشهر وراجع الكشف.', 'لوحة «توزيع التكلفة» توضح أثر الرواتب على كل بند قبل الترحيل.', 'الترحيل يتم من المالية ويُنشئ قيداً واحداً بأبعاد المشاريع.'],
    ['Choose the month and review the sheet.', 'The “cost split” panel shows the effect on each budget line before posting.', 'Finance posts it, creating a single entry tagged by project.'],
  ],
  [
    '/reports/hq',
    'التقرير الشهري للمقر',
    'Monthly HQ report',
    'تقرير جاهز لمقر الصندوق في الكويت: الموقف المالي، تقدّم المشاريع، الأنشطة، المستفيدون، المخزون، والتحديات. يُصدَّر PDF ويُرسل بالبريد بضغطة.',
    'A ready report for headquarters in Kuwait: financial position, project progress, activities, beneficiaries, stock and challenges. Export to PDF and email it in one click.',
    ['اختر الشهر — تمتلئ الأرقام تلقائياً من النظام.', 'عدّل الملخص والتحديات بكلماتك.', '«تنزيل PDF» أو «إرسال بالبريد» — المستلمون والموضوع من إعدادات إرسال التقارير.'],
    ['Pick the month — figures fill in automatically from the system.', 'Edit the summary and challenges in your own words.', '“Download PDF” or “Send by email” — recipients and subject come from Report delivery settings.'],
  ],
  [
    '/reports/donor',
    'تقرير المانح',
    'Donor report',
    'تقرير مشروع واحد حسب المحاور والبنود: الميزانية، المصروف، النسبة، والأنشطة المنفذة.',
    'A single-project report by pillar and line: budget, spent, percentage and activities delivered.',
    ['اختر المشروع والفترة.', 'صدّر PDF لإرفاقه مع التقرير السردي للمانح.'],
    ['Choose the project and period.', 'Export to PDF to attach to your narrative donor report.'],
  ],
  [
    '/reports/expenditure',
    'تقرير المصروفات الربع سنوي',
    'Quarterly expenditure report',
    'نموذج المانح التفصيلي للمصروفات: كل معاملة بنشاطها ورمز التمويل وفئة المصروف والحساب، المصرَّح به مقابل الفعلي.',
    'The donor’s detailed expenditure template: every transaction with activity, fund code, expense category and account, authorized against actual.',
    ['اختر المشروع والربع والعملة (جنيه أو دولار).', 'راجع الجدول ثم «تنزيل Excel» بنفس تنسيق نموذج المانح.', 'لتظهر رموز الأنشطة والتمويل، أنشئ المشروع بـ «استيراد من ملف المانح».'],
    ['Pick the project, quarter and currency (SDG or USD).', 'Check the table, then “Download Excel” in the donor’s template format.', 'To get activity IDs and fund codes, create the project with “Import donor budget”.'],
  ],
  [
    '/reports/statement',
    'كشف حساب المشاريع',
    'Projects statement',
    'كل المشاريع بالميزانية والمستلم والمصروف والمتبقي بالدولار والجنيه، مع إجمالي كل مانح.',
    'Every project with budget, received, spent and remaining in USD and SDG, with totals by donor.',
    ['اختر التاريخ المطلوب الكشف حتى نهايته.', '«تنزيل Excel» لورقتين: المشاريع والمانحون.'],
    ['Pick the as-of date.', '“Download Excel” gives two sheets: Projects and Donors.'],
  ],
  [
    '/supply/procurement',
    'المشتريات',
    'Procurement',
    'دورة الشراء في ملف واحد: طلب شراء، طلب عروض أسعار، مقارنة العروض والترسية، أمر شراء، واستلام مخازن — وكل نموذج يُطبع بقالب المقر.',
    'The purchase cycle in one file: requisition, price request, bid comparison and award, purchase order and stores receipt — each form prints in the head-office template.',
    ['«ملف شراء جديد» وأدخل الأصناف.', 'انتقل بين الخطوات الخمس؛ كل خطوة تُفعّل الحالة التالية عند الحفظ.', 'استخدم زر الطباعة لكل نموذج (يمكن الحفظ PDF من نافذة الطباعة).'],
    ['“New purchase file” and enter the items.', 'Move through the five steps; saving each one advances the file.', 'Use the print button on each form (Save as PDF from the print dialog).'],
  ],
  [
    '/finance/documents',
    'مستندات الدفع',
    'Payment documents',
    'الطلب المالي وشهادة الإنجاز وخطاب العهدة بقالب المقر، مع كتابة المبلغ بالحروف تلقائياً.',
    'The payment request, completion certificate and custody letter in the head-office layout, with the amount written in words automatically.',
    ['اختر المستند ثم طلب صرف معتمداً لتعبئته تلقائياً.', 'عدّل أي حقل ثم «طباعة / حفظ PDF».'],
    ['Choose the document, then an approved request to fill it in.', 'Edit any field, then “Print / save PDF”.'],
  ],
  [
    '/reports/sent',
    'سجل الإرسال',
    'Sent reports',
    'كل تقرير أُرسل: لمن، ومتى، ومن أرسله، مع نسخة PDF.',
    'Every report sent: to whom, when and by whom, with a PDF copy.',
    ['افتح أي سجل لإعادة تنزيل النسخة المرسلة.'],
    ['Open any record to download the copy that was sent.'],
  ],
  [
    '/alerts',
    'التنبيهات',
    'Notifications',
    'كل التنبيهات الموجهة إليك: اعتمادات، مواعيد قريبة، عهد متأخرة، مخزون منخفض، تقارير ناقصة.',
    'All notifications addressed to you: approvals, upcoming deadlines, overdue advances, low stock, missing reports.',
    ['اضغط على التنبيه للانتقال إلى الشيء المعني.', 'لتغيير ما يصلك ومتى، اذهب إلى «قواعد التنبيهات» في الإعدادات.'],
    ['Click a notification to go to what it refers to.', 'To change what you receive and when, go to “Notification rules” in Settings.'],
  ],
  [
    '/alerts/calendar',
    'تقويم المواعيد',
    'Deadline calendar',
    'المواعيد النهائية: تقارير المقر، الإقفال، تقارير المانحين، انتهاء العقود. يصلك تنبيه قبل الموعد بعدد الأيام الذي تحدده.',
    'Deadlines: HQ reports, close, donor reports, contract ends. You are notified the number of days before that you choose.',
    ['«موعد جديد» مع تكرار شهري أو سنوي.', 'حدد «التنبيه قبل» بالأيام لكل موعد.'],
    ['“New deadline” with monthly or yearly repeat.', 'Set “remind me before” in days for each deadline.'],
  ],
  [
    '/settings/organization',
    'إعدادات المؤسسة',
    'Organization settings',
    'اسم المؤسسة وشعارها، والعملة الأساسية، وبداية السنة المالية، واللغة الافتراضية.',
    'Organisation name and logo, base currency, financial year start and default language.',
    ['الشعار يظهر في القائمة وفي كل التقارير وملفات PDF.'],
    ['The logo appears in the menu and on every report and PDF.'],
  ],
  [
    '/settings/offices',
    'المكاتب والفروع',
    'Offices',
    'أضف المكاتب والفروع، وحدد نوعها وموقعها على الخريطة، وفعّلها أو أوقفها.',
    'Add offices and branches, set their type and map position, and activate or deactivate them.',
    ['«مكتب جديد» ثم اضغط على الخريطة لتحديد موقعه.', 'المكتب الموقوف يختفي من القوائم لكن تبقى بياناته.'],
    ['“New office”, then click the map to set its location.', 'A deactivated office disappears from lists but its data stays.'],
  ],
  [
    '/settings/users',
    'المستخدمون',
    'Users',
    'أنشئ حسابات المستخدمين وحدد دور كل منهم ومكتبه.',
    'Create user accounts and set each person’s role and office.',
    ['«مستخدم جديد»: الاسم، البريد، المكتب، الدور.', 'الدور يحدد ما يراه المستخدم وما يستطيع فعله.', 'إيقاف المستخدم يمنع دخوله دون حذف سجلّه.'],
    ['“New user”: name, email, office, role.', 'The role decides what the user sees and can do.', 'Deactivating a user blocks sign-in without deleting their history.'],
  ],
  [
    '/settings/roles',
    'الأدوار والصلاحيات',
    'Roles & permissions',
    'كل دور له مستوى وصول لكل وحدة: لا شيء، عرض، تعديل، إدارة — ونطاق البيانات (مكتبه فقط أو كل المكاتب). الوحدة غير المسموحة لا تظهر في القائمة أصلاً.',
    'Each role has an access level per module — none, view, edit, manage — and a data scope (own office or all). Modules a role cannot access do not appear in its menu at all.',
    ['انسخ دوراً قريباً بدلاً من البدء من الصفر.', 'اضبط مستوى كل وحدة من الجدول.', 'جرّب النتيجة: بدّل المستخدم من القائمة العلوية وشاهد ما يظهر له.'],
    ['Copy a similar role instead of starting from scratch.', 'Set each module’s level in the grid.', 'Try it out: switch user from the top menu and see what they get.'],
    ['مبدأ «الحاجة إلى المعرفة»: أعطِ أقل صلاحية تكفي للعمل.', 'Need-to-know: give the least access that gets the job done.'],
  ],
  [
    '/settings/approval-rules',
    'قواعد الاعتماد',
    'Approval rules',
    'من يعتمد ماذا: حسب المبلغ والمكتب. مثال: حتى 1,000$ مشرف المكتب، وما فوقها يضاف مدير المالية ثم المدير التنفيذي.',
    'Who approves what, by amount and office. Example: up to $1,000 the office supervisor; above that the finance manager, then the executive director.',
    ['أضف شريحة مبلغ وحدد خطوات الاعتماد بالترتيب.', 'يمكن عمل قاعدة خاصة لمكتب معين.', 'التغيير يطبّق على الطلبات الجديدة فقط.'],
    ['Add an amount band and order the approval steps.', 'You can create a rule for a specific office.', 'Changes apply to new requests only.'],
  ],
  [
    '/settings/notifications',
    'قواعد التنبيهات',
    'Notification rules',
    'متى يُرسل التنبيه، ولمن، وعبر أي قناة. مثال: «قبل موعد التقرير بـ 5 أيام، أرسل للمحاسب عبر البريد وواتساب».',
    'When a notification goes out, to whom and on which channel. Example: “5 days before a report deadline, notify the accountant by email and WhatsApp”.',
    ['اختر الحدث (موعد، عهدة متأخرة، مخزون منخفض…).', 'حدد الحد (عدد الأيام أو النسبة).', 'اختر المستلمين والقنوات، ثم فعّل القاعدة.'],
    ['Choose the event (deadline, overdue advance, low stock…).', 'Set the threshold (days or percentage).', 'Choose recipients and channels, then switch the rule on.'],
  ],
  [
    '/settings/channels',
    'البريد وواتساب والرسائل',
    'Email, WhatsApp & SMS',
    'نافذة واحدة لإعداد القنوات الثلاث. مصممة ليقوم بها قسم تقنية المعلومات بأنفسهم: اختر المزوّد، الصق البيانات، اضغط «اختبار».',
    'One window to set up all three channels, designed for your IT team to do themselves: pick the provider, paste the details, press “Test”.',
    ['اختر المزوّد الجاهز (Gmail، Outlook، Twilio…) — تمتلئ الإعدادات الأساسية.', 'أدخل البريد/المفتاح ثم «إرسال رسالة اختبار».', 'فعّل القناة أو أوقفها بالمفتاح.'],
    ['Pick a ready preset (Gmail, Outlook, Twilio…) — the basic settings fill in.', 'Enter the email or key, then “Send a test message”.', 'Switch each channel on or off with its toggle.'],
  ],
  [
    '/settings/reports',
    'إعدادات إرسال التقارير',
    'Report delivery',
    'لمن يُرسل التقرير الشهري، والموضوع ونص الرسالة. يمكن استخدام متغيرات مثل {month} و{sender}.',
    'Who receives the monthly report, and the subject and message body. You can use placeholders such as {month} and {sender}.',
    ['أضف عناوين المستلمين والنسخ.', 'المعاينة توضح الرسالة كما ستصل.'],
    ['Add recipients and CC addresses.', 'The preview shows the message as it will arrive.'],
  ],
]

export const articles: HelpArticle[] = rows.map(([path, tAr, tEn, wAr, wEn, sAr, sEn, tip]) => ({
  path,
  title: { ar: tAr, en: tEn },
  what: { ar: wAr, en: wEn },
  steps: { ar: sAr, en: sEn },
  tip: tip ? { ar: tip[0], en: tip[1] } : undefined,
}))

/** The article for a pathname — exact match first, then the closest parent (e.g. /projects/pa → /projects). */
export function articleFor(pathname: string): HelpArticle | undefined {
  const exact = articles.find((a) => a.path === pathname)
  if (exact) return exact
  return articles
    .filter((a) => a.path !== '/' && pathname.startsWith(a.path + '/'))
    .sort((a, b) => b.path.length - a.path.length)[0]
}

export const faqs: { q: Bi; a: Bi }[] = [
  {
    q: { ar: 'لماذا لا أرى وحدة المالية (أو غيرها) في القائمة؟', en: 'Why can’t I see Finance (or another module) in the menu?' },
    a: { ar: 'القائمة تعرض فقط ما يسمح به دورك. إذا احتجت وحدة إضافية اطلب من مسؤول النظام تعديل دورك في «الأدوار والصلاحيات».', en: 'The menu only shows what your role allows. If you need another module, ask the system administrator to adjust your role under “Roles & permissions”.' },
  },
  {
    q: { ar: 'كيف أرى مكتباً واحداً فقط؟', en: 'How do I see just one office?' },
    a: { ar: 'إذا كان دورك يرى كل المكاتب فستجد في أعلى الصفحة قائمة «كل المكاتب». اختر مكتباً فتعرض لوحة القيادة والطلبات والأنشطة والمالية وغيرها هذا المكتب فقط، ويُحفظ اختيارك. اضغط × للعودة إلى كل المكاتب. أما سقوف المشاريع فتبقى مشتركة بين المكاتب. من يعمل في مكتب واحد يرى مكتبه فقط ولا تظهر له القائمة.', en: 'If your role can see every office, you will find an “All offices” menu at the top of the page. Pick an office and the dashboard, requests, activities, finance and other pages show that office only; your choice is remembered. Press × to go back to all offices. Project ceilings stay shared across offices. People who work in a single office see only their own office and do not get the menu.' },
  },
  {
    q: { ar: 'رفضني النظام لأن المبلغ يتجاوز السقف. ماذا أفعل؟', en: 'The system stopped me because the amount exceeds the ceiling. What now?' },
    a: { ar: 'اطلب «إعادة تخصيص» لنقل مبلغ من بند آخر لديه متاح، أو قسّم الطلب. إعادة التخصيص تمرّ على اعتماد.', en: 'Request a “reallocation” to move money from another line that has room, or split the request. Reallocations go through approval.' },
  },
  {
    q: { ar: 'انقطع الإنترنت أثناء رفع تقرير. هل ضاع؟', en: 'The internet dropped while I was sending a report. Is it lost?' },
    a: { ar: 'لا. يُحفظ التقرير على جهازك ويُرسل عند عودة الاتصال. للمكاتب التي يطول انقطاعها استخدم قالب Excel.', en: 'No. It is kept on your device and sent when the connection returns. For offices offline for long periods, use the Excel template.' },
  },
  {
    q: { ar: 'ما الفرق بين التمويل النقدي والتغذية؟', en: 'What is the difference between cash funding and replenishment (التغذية)?' },
    a: { ar: 'الدعم النقدي يدخل المالية كإيراد في البنك. التغذية مواد عينية تدخل سلسلة الإمداد كمخزون، وتُسجّل محاسبياً كتبرعات عينية بقيمتها.', en: 'Cash support goes to Finance as income in the bank. Replenishment is in-kind goods that go into the supply chain as stock, and are booked as in-kind donations at their value.' },
  },
  {
    q: { ar: 'كيف أغيّر من يعتمد طلبات مكتبي؟', en: 'How do I change who approves my office’s requests?' },
    a: { ar: 'من «قواعد الاعتماد» في الإعدادات — يمكن عمل قاعدة خاصة لكل مكتب وحسب شرائح المبلغ.', en: 'Under “Approval rules” in Settings — you can make a rule per office and by amount band.' },
  },
  {
    q: { ar: 'كيف أبدّل بين العربية والإنجليزية؟', en: 'How do I switch between Arabic and English?' },
    a: { ar: 'الزر «EN» / «ع» في الشريط العلوي. يُحفظ اختيارك لهذا الجهاز.', en: 'The “EN” / “ع” button in the top bar. Your choice is remembered on this device.' },
  },
]

export const glossary: { term: Bi; def: Bi }[] = [
  { term: { ar: 'السقف', en: 'Ceiling' }, def: { ar: 'الحد الأعلى المسموح صرفه على بند أو محور أو مشروع.', en: 'The maximum that can be spent on a line, pillar or project.' } },
  { term: { ar: 'المحجوز', en: 'Committed' }, def: { ar: 'مبالغ معتمدة لم تُدفع بعد، أو عُهد مفتوحة — تُخصم من المتاح.', en: 'Amounts approved but not yet paid, or open advances — they reduce what is available.' } },
  { term: { ar: 'العهدة', en: 'Advance' }, def: { ar: 'مبلغ يُسلّم لموظف قبل النشاط ويُسوّى بالفواتير بعده.', en: 'Money given to a staff member before an activity and settled with receipts afterwards.' } },
  { term: { ar: 'إعادة التخصيص', en: 'Reallocation' }, def: { ar: 'نقل مبلغ من بند إلى آخر ضمن المشروع، بموافقة.', en: 'Moving money from one line to another within a project, with approval.' } },
  { term: { ar: 'التغذية', en: 'Replenishment' }, def: { ar: 'المواد العينية الواردة من المقر أو المانحين إلى المخازن.', en: 'In-kind goods arriving from HQ or donors into the stores.' } },
  { term: { ar: 'إعادة التقييم', en: 'Revaluation' }, def: { ar: 'تعديل أرصدة الجنيه بسعر نهاية الشهر وتسجيل الفرق ربحاً أو خسارة.', en: 'Restating SDG balances at the month-end rate and booking the difference as a gain or loss.' } },
  { term: { ar: 'ميزان المراجعة', en: 'Trial balance' }, def: { ar: 'قائمة بأرصدة كل الحسابات؛ يجب أن يتساوى فيها المدين والدائن.', en: 'A list of every account balance; debits must equal credits.' } },
  { term: { ar: 'الأبعاد', en: 'Dimensions' }, def: { ar: 'المشروع والبند والمكتب المرفقة بكل سطر قيد، لتقارير المشاريع.', en: 'The project, line and office attached to each entry line, for project reporting.' } },
]

export interface TourStep {
  target?: string // CSS selector; omitted = centred card
  title: Bi
  body: Bi
}

export const mainTour: TourStep[] = [
  {
    title: { ar: 'أهلاً بك في نظام إدارة الموارد', en: 'Welcome to the ERP' },
    body: { ar: 'جولة قصيرة (دقيقة واحدة) لتتعرف على مكان كل شيء. يمكنك إعادتها لاحقاً من مركز المساعدة.', en: 'A short one-minute tour so you know where everything is. You can replay it any time from the Help centre.' },
  },
  {
    target: '[data-tour=sidebar]',
    title: { ar: 'القائمة الرئيسية', en: 'Main menu' },
    body: { ar: 'تظهر هنا الوحدات المسموحة لدورك فقط. اضغط على الوحدة لتفتح صفحاتها الفرعية. الأرقام الحمراء = أشياء تنتظرك.', en: 'Only the modules your role allows appear here. Click a module to open its pages. Red numbers mean something is waiting for you.' },
  },
  {
    target: '[data-tour=search]',
    title: { ar: 'ابحث أو انتقل', en: 'Search or jump' },
    body: { ar: 'اكتب اسم أي صفحة أو طلب أو مشروع للانتقال إليه مباشرة. اختصار لوحة المفاتيح: Ctrl + K.', en: 'Type the name of any page, request or project to jump straight to it. Keyboard shortcut: Ctrl + K.' },
  },
  {
    target: '[data-tour=lang]',
    title: { ar: 'اللغة', en: 'Language' },
    body: { ar: 'بدّل بين العربية والإنجليزية في أي وقت.', en: 'Switch between Arabic and English at any time.' },
  },
  {
    target: '[data-tour=bell]',
    title: { ar: 'التنبيهات', en: 'Notifications' },
    body: { ar: 'الاعتمادات، المواعيد القريبة، العهد المتأخرة، المخزون المنخفض — كلها تصل هنا، وبالبريد أو واتساب إن فُعّلت.', en: 'Approvals, upcoming deadlines, overdue advances, low stock — they all arrive here, and by email or WhatsApp if switched on.' },
  },
  {
    target: '[data-tour=user]',
    title: { ar: 'حسابك', en: 'Your account' },
    body: { ar: 'هنا تسجّل الخروج. في هذا العرض التجريبي يمكنك أيضاً تجربة النظام بدور مستخدم آخر.', en: 'Sign out from here. In this demo you can also try the system as another user.' },
  },
  {
    target: '[data-tour=page-help]',
    title: { ar: 'مساعدة في كل صفحة', en: 'Help on every page' },
    body: { ar: 'زر «؟» بجانب عنوان كل صفحة يشرح ما هي وكيف تستخدمها خطوة بخطوة.', en: 'The “?” button next to each page title explains what the page is for and how to use it, step by step.' },
  },
]
